### ISSUE TITLE
Validate the UUID of each pilot

### ISSUE THREAD

**Issue by klaasnicolaas** [FPVScores/FPVScores-Sync#44]
It might be useful if the plugin checks if a UUID is valid and if not returns it in the API response. It can be quite error-prone to enter a wrong UUID.

**Comment by JesseFPV** [comment]
Currently there is no way to indicate this correctly on the pilot UI. However tools are on the list to make it easier to import pilot uuid's from QR-code scanning and cloud import functions. Will close it for now.
