### ISSUE TITLE
Version number in RH under "settings" does not match

### ISSUE THREAD

**Issue by SentinelFour** [FPVScores/FPVScores-Sync#48]
Hi, to be verified, but unless I made a mistake when installing the latest version 1.2, the version number under settings in RotorHazard does not match and has not been updated since the previous version:

<img width="848" alt="image" src="https://github.com/user-attachments/assets/7ceac862-088e-4431-9025-b85511bbf2ad" />

**Comment by JesseFPV** [comment]
Fixed!
